### ISSUE TITLE
Fullscreen exit icon stays when entering fullscreen mode

### ISSUE THREAD

**Issue by RogerioTDS** [rafaelmardojai/firefox-gnome-theme#560]
**Describe the bug**
A clear and concise description of what the bug is: Hello, I'm facing the same issue as #476.
The problem happens in any full screen, be it Youtube, Netflix or any other website.

**Setup information**
 - OS: Archlinux
 - Installation method: Official Arch repositories
 - Firefox version: 110
 - Theme version: commit 356ad32
 - Optional features enabled: 
gnomeTheme.hideSingleTab
gnomeTheme.activeTabContrast
gnomeTheme.systemIcons

**Additional context**
The v109 version of the theme already faced this problem.

**Comment by rafaelmardojai** [comment]
Sadly I can't reproduce this since #476 was fixed.

**Comment by RogerioTDS** [comment]
I don't know if this helps, but I'm sending a full screen print, where, in the upper right corner, the icon to enter and exit full screen is always on display.
To reproduce the bug: open Youtube, Netflix, or any other site that contains video, put the video in full screen. The icon, to enter and exit full screen, will always be visible in the upper right corner, as shown in the screenshot.
What else can I do to help identify the problem?
/home/rogeriotds/Imagens/Capturas de tela/Captura de tela de 2023-02-17 16-03-57.png

**Comment by Matthis-F** [comment]
Hi,
I'm also experiencing this issue (c.f screenshot below).

**Setup information :**
- OS: **Archlinux**
- Firefox ver. : **111.0.1**
- Theme version commit : a6d79e853119b57024c72bb9156474ce37efbee7 
- Optional features enabled: None

It's also very distracting on a 16:10 display.
Is there any debugging steps I can do to help ?

![image](https://user-images.githubusercontent.com/36378391/230791320-e31f78e0-f421-4a39-b89a-d8583f2afb10.png)

**Comment by n1ckoates** [comment]
I'm still having this issue on the latest version of the theme, though my fullscreen icon is on the upper left instead of the upper right.
