### ISSUE TITLE
Firefox 132 Mute Button is UNHOLY

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#837]
Exorcise this button please
![Screenshot From 2024-10-02 03-49-11](https://github.com/user-attachments/assets/de0f0de2-c2f1-4823-985c-9a3c6048a309)

**Comment by rien333** [comment]
Can't reproduce, please provide more information about your installation (firefox version, firefox-gnome-theme-version, OS/distro, etc.)

**Comment by KUPOinyourWINDOW** [comment]
Firefox 132 beta 1, Flatpak, Fedora 41, Gnome 47,
every tab that plays media has this cursed mute button because Firefox has updated the mute button visuals

**Comment by rien333** [comment]
Sorry, I'm stupid and confused 132 with 131 for a second. My bad. Guess said info can still be helpful 🙂

**Comment by rafaelmardojai** [comment]
Fixed in `beta` branch.

**Comment by KUPOinyourWINDOW** [comment]
Can confirm, its fixed! Thank you as always, love the theme and appreciate your work, will continue to report beta bugs as they come to help!

**Comment by rien333** [comment]
FIY, this was release today, and the mute buttons indeed look unholy. Thanks for your work!

**Comment by iaacornus** [comment]
for some reason, the problem still persists in my firefox despite of update, ff132, silverblue 41
